version: '3'
services:
  postgresql:
    container_name: industrial-consulting-postgresql 
    image: postgres:latest 
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: industrial_consulting
    ports:
     - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  flask:
    container_name: industrial-consulting-flask
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:  
      - "5000:5000"
    depends_on:
      - postgresql
    network_mode: "host"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgresql:5432/industrial_consulting
    volumes:
      - ./backend:/app

  
  vuejs:
    container_name: industrial-consulting-vuejs
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:  
      - "8080:8080"
    depends_on:
      - flask
    


volumes: 
  data:
